apiVersion: v1
kind: Namespace
metadata:
  name: node
  labels:
    app: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: node
  labels:
    app: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: yershalom/testnode:v1
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3000"
        - name: REGION
          value: us-east-1
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: node
spec:
    selector:
      app: node
    ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000