apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: generic
  namespace: flux-system
spec:
  type: generic
  address: http://node-service.node.svc.cluster.local:3000/event