apiVersion: v1
kind: Namespace
metadata:
  name: python
  labels:
    app: python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: python
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: yershalom/testnode:v1
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3000"
        - name: REGION
          value: us-east-1
        - name: FOO
          value: bar
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: python
spec:
    selector:
      app: python
    ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000